#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform writeonly image2D framebufferImage;


layout(push_constant) uniform Params 
{
	vec2 resolution;
	float time;
	float pad;
} params;

void main()
{
	vec2 p = (-params.resolution.xy + 2.0 * vec2(gl_GlobalInvocationID.xy)) / params.resolution.y;

	vec4 res = vec4(vec3(1.0-smoothstep(0.0, 0.01, abs(length(p)-0.5*abs(sin(params.time))))), 1.0);
	
	imageStore(framebufferImage, ivec2(gl_GlobalInvocationID.xy), res);
}
